name: CI Pull Request

on:
  pull_request:
    branches: [master, main, develop]
  workflow_dispatch:

jobs:
  ci-check:
    name: CI Check
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Build
        run: |
          cmd /c "msbuild MissionPlanner.sln /p:Configuration=Debug /p:Platform=\"Any CPU\" /verbosity:minimal"
          cmd /c "msbuild MissionPlanner.sln /p:Configuration=Release /p:Platform=\"Any CPU\" /verbosity:minimal"